### ISSUE TITLE
Can you update with 2.12

### ISSUE THREAD

**Issue by sanojlawrence** [squti/ExoPlayer-MKV-Sample#1]
Many function are deprecated, update with 2.12

**Comment by squti** [comment]
Which functions are deprecated?

**Comment by sanojlawrence** [comment]
![Untitled](https://user-images.githubusercontent.com/7949017/98263892-53c2a300-1fad-11eb-8488-2103d2fabf52.png)


And also some time i get this error. but the same video is played when try to play it again. Am working with `2.12.1` exoplayer version.

`2020-11-05 21:24:01.207 6374-6815/com.example.jlplayer E/ACodec: [OMX.IMG.MSVDX.Decoder.AVC] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2020-11-05 21:24:01.691 6374-6606/com.example.jlplayer E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
2020-11-05 21:24:03.184 6374-6834/com.example.jlplayer E/BufferQueueProducer: [] Can not get hwsched service
2020-11-05 21:24:03.525 6374-6605/com.example.jlplayer E/MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
2020-11-05 21:24:04.992 6374-6854/com.example.jlplayer E/BufferQueueProducer: [] Can not get hwsched service
2020-11-05 21:24:04.997 6374-6849/com.example.jlplayer E/ACodec: [OMX.IMG.MSVDX.Decoder.AVC] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2020-11-05 21:24:05.090 677-1317/? E/BufferQueueProducer: [SurfaceView - com.example.jlplayer/Activity.VideoPlayer#0] setMaxDequeuedBufferCount: requested buffer count 1 is less than minimum 2
2020-11-05 21:24:05.091 6374-6849/com.example.jlplayer E/Surface: IGraphicBufferProducer::setBufferCount(1) returned Invalid argument
2020-11-05 21:24:05.092 6374-6849/com.example.jlplayer E/ACodec: native_window_set_buffer_count failed: Invalid argument (22)
2020-11-05 21:24:05.099 6374-6846/com.example.jlplayer E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1967)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1242)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:516)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:478)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1402)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1368)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1343)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2020-11-05 21:24:05.316 1145-7119/? E/WindowManager: win=Window{90a8b32 u0 com.example.jlplayer/Activity.FVideoActivity} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false`
